In [1]:
import numpy as np

In [42]:
arr1 = np.array([1,2,3]) # 1차원 배열 -> []
arr2 = np.array([[1,2,3],[1,2,3]]) # 2차원 배열 -> [[]]
arr3 = np.array([[[1,2,3,],[1,2,3]],[[1,2,3,],[1,2,3]]]) # 3차원 배열 -> [[[]]]

In [57]:
# 배열형태(shape)

print('arr1 배열 형태:{}\narr2 배열 형태:{}\narr 배열 형태:{}\n'.format(arr1.shape,arr2.shape,arr3.shape))

arr1 배열 형태:(3,)
arr2 배열 형태:(2, 3)
arr 배열 형태:(2, 2, 3)



In [58]:
# 배열차원(ndim)

print('arr1:{}차원\narr2:{}차원\narr3:{}차원'.format(arr1.ndim,arr2.ndim,arr3.ndim))

arr1:1차원
arr2:2차원
arr3:3차원


In [45]:
list = [1,2,3]
array = np.array([1,2,3])

In [59]:
# 데이터 타입(dtype)

print(type(list))
print(type(array))
print("array =",array,"\narray 타입 :",array.dtype)

<class 'list'>
<class 'numpy.ndarray'>
array = [1 2 3] 
array 타입 : int32


In [49]:
int_arr = np.array([1,2,3])
float_arr = int_arr.astype('float64')

In [60]:
# 데이터 타입 변환(astype)

print(float_arr,float_arr.dtype)

[1. 2. 3.] float64


In [61]:
# 데이터 순차적 삽입 - 범위지정(stop값)

s_arr = np.arange(20) 
# 배열명 = arange(인자값) -> 배열에 0부터 arange함수의 인자값-1 까지 순차적으로 ndarray의 데이터 값으로 변환하여 삽입
print(s_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [54]:
# 데이터 순차적 삽입 - 범위지정(start값,stop값)

s_arr2 = np.arange(2,5)
# 배열명 = arange(인자값1,인자값2) -> 배열에 arange함수의 인자값1부터 인자값2-1 까지 순차적으로 ndarray의 데이터 값으로 변환하여 삽입
print(s_arr2)

[2 3 4]


In [4]:
# 0으로 채워진 튜플 생성

zero_array = np.zeros((3,2), dtype='int32') -> [ [0,0], [0,0], [0,0] ]
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [8]:
# 1로 채워진 튜플 생성

one_array = np.ones((3,2))
# 함수 인자로 dtype를 지정하지 않으면 float64형태로 튜플 생성
one_array2 = np.ones((3,2), dtype='int64')
print("[one_array]\n", one_array, "\ntype : ", one_array.dtype, "\n")
print("[one_array2]\n", one_array2, "\ntype : ", one_array2.dtype)

[one_array]
 [[1. 1.]
 [1. 1.]
 [1. 1.]] 
type :  float64 

[one_array2]
 [[1 1]
 [1 1]
 [1 1]] 
type :  int64


In [31]:
# 차원 변경

arr = np.arange(10)
print(f'{arr.ndim}차원 arr:\n',arr)

arr2 = arr.reshape(2,5)
print(f'\n{arr2.ndim}차원 arr:\n',arr2)

arr3 = arr.reshape(5,2)
print(f'\n{arr3.ndim}차원 arr:\n',arr3)

arr4 = arr.reshape(-1,5)
# -1을 인자로 적용 -> 원래 array와 호환되는 차원으로 자동 변환
print(f'\n{arr4.ndim}차원 arr:\n',arr4)

# 리스트 자료형으로 변환
list = arr4.tolist()
print(f'List:\n{list}')

1차원 arr:
 [0 1 2 3 4 5 6 7 8 9]

2차원 arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

2차원 arr:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

2차원 arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

List:
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


In [67]:
# 1차원 단일 값 추출

arr = np.arange(0,10)
print(arr)
print(f'arr[0]: {arr[0]}')
# index 번호{시작 : 0, 끝 : 9}

# 수정
arr[0] = 1
print(f'[수정] arr[0]: {arr[0]}')


# 2차원 단일 값 추출
arr2 = np.arange(0,10)
arr2 = arr2.reshape(2,5)
print(f'\n2차원:\n{arr2}')
print(f'arr2[0,0]: {arr2[0,0]}')

# 수정
arr2[0,0] = 2
print(f'[수정] arr2[0,0]: {arr2[0,0]}')

[0 1 2 3 4 5 6 7 8 9]
arr[0]: 0
[수정] arr[0]: 1

2차원:
[[0 1 2 3 4]
 [5 6 7 8 9]]
arr2[0,0]: 0
[수정] arr2[0,0]: 2


In [66]:
#슬라이싱

# 1차원 다중 값 추출

arr = np.arange(0,10)
print(arr)
print(f'arr[2:5]: {arr[2:5]}')

print(f'arr[:5]: {arr[:5]}')
print(f'arr[:]: {arr[:]}')
# 슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략 가능


# 2차원 다중 값 추출

arr2 = np.arange(0,25)
arr2 = arr2.reshape(5,5)
print(f'\n2차원:\n{arr2}')
print(f'arr2[2:4,0:1]:\n{arr2[2:4,0:2]}')

print(f'\nrow=0 : {arr2[0]}')
# row가 0인 값들 출력

[0 1 2 3 4 5 6 7 8 9]
arr[2:5]: [2 3 4]
arr[:5]: [0 1 2 3 4]
arr[:]: [0 1 2 3 4 5 6 7 8 9]

2차원:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
arr2[2:4,0:1]:
[[10 11]
 [15 16]]

row=0 : [0 1 2 3 4]


In [110]:
# 불린 인덱싱

arr = np.arange(1,10)
print(arr)

print('arr[arr > 5] :',arr[arr > 5])

boolArr = np.array([False, False, False, False, False, True, True, True, True])
print('\nboolArr :',boolArr)
print('arr[boolArr] :', arr[boolArr])

numArr = np.array([5,6,7,8])
print('\nnumArr :',numArr)
print('arr[numArr] :', arr[numArr])

[1 2 3 4 5 6 7 8 9]
arr[arr > 5] : [6 7 8 9]

boolArr : [False False False False False  True  True  True  True]
arr[boolArr] : [6 7 8 9]

numArr : [5 6 7 8]
arr[numArr] : [6 7 8 9]


In [38]:
# 행렬의 정렬

# 1차원
arr = np.array([2,3,4,6,1,5,9,7,8,11,10])

# np.sort(array)
# 원본 변화 없음, 정렬된 값 반환
# 오름차순
print(f'np.sort() - [Before] original array : {arr}')
print(f'np.sort() - return value : {np.sort(arr)}')
print(f'np.sort() - [After] original array : {arr}\n')
# 내림차순
print(f'np.sort() - [Before] original array : {arr}')
print(f'np.sort() - return value : {np.sort(arr)[::-1]}')
print(f'np.sort() - [After] original array : {arr}\n')

# array.sort()
# 원본 변화, 반환 없음
print(f'array.sort() - [Before] original array : {arr}')
print(f'array.sort() - return value : {arr.sort()}')
print(f'array.sort() - [After] original array : {arr}\n')


# 2차원
arr2 = np.array([[3,4],[2,1]])

# row 방향 정렬
print(f'row sort - [Before]\n{arr2}')
print(f'row sort - [After]\n{np.sort(arr2, axis=0)}')

# calumn 방향 정렬
print(f'column sort - [Before]\n{arr2}')
print(f'column sort - [After]\n{np.sort(arr2, axis=1)}')

np.sort() - [Before] original array : [ 2  3  4  6  1  5  9  7  8 11 10]
np.sort() - return value : [ 1  2  3  4  5  6  7  8  9 10 11]
np.sort() - [After] original array : [ 2  3  4  6  1  5  9  7  8 11 10]

np.sort() - [Before] original array : [ 2  3  4  6  1  5  9  7  8 11 10]
np.sort() - return value : [11 10  9  8  7  6  5  4  3  2  1]
np.sort() - [After] original array : [ 2  3  4  6  1  5  9  7  8 11 10]

array.sort() - [Before] original array : [ 2  3  4  6  1  5  9  7  8 11 10]
array.sort() - return value : None
array.sort() - [After] original array : [ 1  2  3  4  5  6  7  8  9 10 11]

row sort - [Before]
[[3 4]
 [2 1]]
row sort - [After]
[[2 1]
 [3 4]]
column sort - [Before]
[[3 4]
 [2 1]]
column sort - [After]
[[3 4]
 [1 2]]


In [52]:
# 정렬된 행렬 인덱스

# 오름차순
arr3 = np.array([3,4,2,1])
print(f'[Before]\narray : {arr3}\narr3[0] : {arr3[0]}\narr3[1] : {arr3[1]}\narr3[2] : {arr3[2]}\narr3[3] : {arr3[3]}')
print(f'np.argsort() - return value(= index array) : {np.argsort(arr3)}')
print(f'[After]\narray : {arr3}\narr3[0] : {arr3[0]}\narr3[1] : {arr3[1]}\narr3[2] : {arr3[2]}\narr3[3] : {arr3[3]}\n')

# 내림차순
arr3 = np.array([3,4,2,1])
print(f'[Before]\narray : {arr3}\narr3[0] : {arr3[0]}\narr3[1] : {arr3[1]}\narr3[2] : {arr3[2]}\narr3[3] : {arr3[3]}')
print(f'np.argsort() - return value(= index array) : {np.argsort(arr3)[::-1]}')
print(f'[After]\narray : {arr3}\narr3[0] : {arr3[0]}\narr3[1] : {arr3[1]}\narr3[2] : {arr3[2]}\narr3[3] : {arr3[3]}')

[Before]
array : [3 4 2 1]
arr3[0] : 3
arr3[1] : 4
arr3[2] : 2
arr3[3] : 1
np.argsort() - return value(= index array) : [3 2 0 1]
[After]
array : [3 4 2 1]
arr3[0] : 3
arr3[1] : 4
arr3[2] : 2
arr3[3] : 1

[Before]
array : [3 4 2 1]
arr3[0] : 3
arr3[1] : 4
arr3[2] : 2
arr3[3] : 1
np.argsort() - return value(= index array) : [1 0 2 3]
[After]
array : [3 4 2 1]
arr3[0] : 3
arr3[1] : 4
arr3[2] : 2
arr3[3] : 1


In [58]:
# 정렬된 행렬 인덱스 응용
name = np.array(['c','d','b','a'])
number = np.array([3,4,2,1])
print(f'name : {name}')
print(f'number : {number}')

sortIndex = np.argsort(number)
print(f'sortIndex : {sortIndex}')
print(f'name[sortIndex] : {name[sortIndex]}')
# 오름차순 정렬 된 행렬의 인덱스 배열을 이용하며 다른 배열을 정렬할 수 있다.

name : ['c' 'd' 'b' 'a']
number : [3 4 2 1]
sortIndex : [3 2 0 1]
name[sortIndex] : ['a' 'b' 'c' 'd']


In [78]:
# 행렬 내적 (행렬 곱)

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[9,10],[11,12]])
print(f'#[a]#\n{a}\n\n    X    \n\n#[b]#\n{b}\n\n    =    \n\n#[a x b]#\n{np.dot(a,b)}')
# (1*7)+(2*9)+(3*11) = 58
# (1*8)+(2*10)+(3*12) = 64
# (4*7)+(5*9)+(6*11) = 139
# (4*8)+(5*10)+(6*12) = 154

#[a]#
[[1 2 3]
 [4 5 6]]

    X    

#[b]#
[[ 7  8]
 [ 9 10]
 [11 12]]

    =    

#[a x b]#
[[ 58  64]
 [139 154]]


In [82]:
# 전치 행렬 (행과 열 위치 변경)
# ex) 1행 2열 -> 2행 1열

# 전치 행렬의 표기
# ex) A의 전치행렬 -> A^T로 표기

A = np.array([[1,2],[3,4]])
print(f'[A]\n{A}\n')
print(f'[A^T]\n{np.transpose(A)}')

# 전치 행렬의 과정
# LinK : https://postfiles.pstatic.net/MjAxODExMjBfNDgg/MDAxNTQyNjc5MzA4MzUw.bm1km4zwly2-P1fZDmPOZaJDXsZdDxP0Cgtj6x14VJ0g.BUxuDViRL6-ZWgANsbUiS16EdtGGt5eFS_IhikfZ3Mkg.GIF.qbxlvnf11/Matrix_transpose.gif?type=w773

[A]
[[1 2]
 [3 4]]

[A^T]
[[1 3]
 [2 4]]


In [ ]:
# 넘파이 기초 끝!!!