In [84]:
import numpy as np

In [42]:
arr1 = np.array([1,2,3]) # 1차원 배열 -> []
arr2 = np.array([[1,2,3],[1,2,3]]) # 2차원 배열 -> [[]]
arr3 = np.array([[[1,2,3,],[1,2,3]],[[1,2,3,],[1,2,3]]]) # 3차원 배열 -> [[[]]]

In [57]:
# 배열형태(shape)

print('arr1 배열 형태:{}\narr2 배열 형태:{}\narr 배열 형태:{}\n'.format(arr1.shape,arr2.shape,arr3.shape))

arr1 배열 형태:(3,)
arr2 배열 형태:(2, 3)
arr 배열 형태:(2, 2, 3)



In [58]:
# 배열차원(ndim)

print('arr1:{}차원\narr2:{}차원\narr3:{}차원'.format(arr1.ndim,arr2.ndim,arr3.ndim))

arr1:1차원
arr2:2차원
arr3:3차원


In [45]:
list = [1,2,3]
array = np.array([1,2,3])

In [59]:
# 데이터 타입(dtype)

print(type(list))
print(type(array))
print("array =",array,"\narray 타입 :",array.dtype)

<class 'list'>
<class 'numpy.ndarray'>
array = [1 2 3] 
array 타입 : int32


In [49]:
int_arr = np.array([1,2,3])
float_arr = int_arr.astype('float64')

In [60]:
# 데이터 타입 변환(astype)

print(float_arr,float_arr.dtype)

[1. 2. 3.] float64


In [61]:
# 데이터 순차적 삽입 - 범위지정(stop값)

s_arr = np.arange(20) 
# 배열명 = arange(인자값) -> 배열에 0부터 arange함수의 인자값-1 까지 순차적으로 ndarray의 데이터 값으로 변환하여 삽입
print(s_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [54]:
# 데이터 순차적 삽입 - 범위지정(start값,stop값)

s_arr2 = np.arange(2,5)
# 배열명 = arange(인자값1,인자값2) -> 배열에 arange함수의 인자값1부터 인자값2-1 까지 순차적으로 ndarray의 데이터 값으로 변환하여 삽입
print(s_arr2)

[2 3 4]


In [4]:
# 0으로 채워진 튜플 생성

zero_array = np.zeros((3,2), dtype='int32') -> [ [0,0], [0,0], [0,0] ]
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [8]:
# 1로 채워진 튜플 생성

one_array = np.ones((3,2))
# 함수 인자로 dtype를 지정하지 않으면 float64형태로 튜플 생성
one_array2 = np.ones((3,2), dtype='int64')
print("[one_array]\n", one_array, "\ntype : ", one_array.dtype, "\n")
print("[one_array2]\n", one_array2, "\ntype : ", one_array2.dtype)

[one_array]
 [[1. 1.]
 [1. 1.]
 [1. 1.]] 
type :  float64 

[one_array2]
 [[1 1]
 [1 1]
 [1 1]] 
type :  int64


In [31]:
# 차원 변경

arr = np.arange(10)
print(f'{arr.ndim}차원 arr:\n',arr)

arr2 = arr.reshape(2,5)
print(f'\n{arr2.ndim}차원 arr:\n',arr2)

arr3 = arr.reshape(5,2)
print(f'\n{arr3.ndim}차원 arr:\n',arr3)

arr4 = arr.reshape(-1,5)
# -1을 인자로 적용 -> 원래 array와 호환되는 차원으로 자동 변환
print(f'\n{arr4.ndim}차원 arr:\n',arr4)

# 리스트 자료형으로 변환
list = arr4.tolist()
print(f'List:\n{list}')

1차원 arr:
 [0 1 2 3 4 5 6 7 8 9]

2차원 arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

2차원 arr:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

2차원 arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

List:
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


In [67]:
# 1차원 단일 값 추출

arr = np.arange(0,10)
print(arr)
print(f'arr[0]: {arr[0]}')
# index 번호{시작 : 0, 끝 : 9}

# 수정
arr[0] = 1
print(f'[수정] arr[0]: {arr[0]}')


# 2차원 단일 값 추출
arr2 = np.arange(0,10)
arr2 = arr2.reshape(2,5)
print(f'\n2차원:\n{arr2}')
print(f'arr2[0,0]: {arr2[0,0]}')

# 수정
arr2[0,0] = 2
print(f'[수정] arr2[0,0]: {arr2[0,0]}')

[0 1 2 3 4 5 6 7 8 9]
arr[0]: 0
[수정] arr[0]: 1

2차원:
[[0 1 2 3 4]
 [5 6 7 8 9]]
arr2[0,0]: 0
[수정] arr2[0,0]: 2


In [66]:
#슬라이싱

# 1차원 다중 값 추출

arr = np.arange(0,10)
print(arr)
print(f'arr[2:5]: {arr[2:5]}')

print(f'arr[:5]: {arr[:5]}')
print(f'arr[:]: {arr[:]}')
# 슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략 가능


# 2차원 다중 값 추출

arr2 = np.arange(0,25)
arr2 = arr2.reshape(5,5)
print(f'\n2차원:\n{arr2}')
print(f'arr2[2:4,0:1]:\n{arr2[2:4,0:2]}')

print(f'\nrow=0 : {arr2[0]}')
# row가 0인 값들 출력

[0 1 2 3 4 5 6 7 8 9]
arr[2:5]: [2 3 4]
arr[:5]: [0 1 2 3 4]
arr[:]: [0 1 2 3 4 5 6 7 8 9]

2차원:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
arr2[2:4,0:1]:
[[10 11]
 [15 16]]

row=0 : [0 1 2 3 4]


In [110]:
# 불린 인덱싱

arr = np.arange(1,10)
print(arr)

print('arr[arr > 5] :',arr[arr > 5])

boolArr = np.array([False, False, False, False, False, True, True, True, True])
print('\nboolArr :',boolArr)
print('arr[boolArr] :', arr[boolArr])

numArr = np.array([5,6,7,8])
print('\nnumArr :',numArr)
print('arr[numArr] :', arr[numArr])

[1 2 3 4 5 6 7 8 9]
arr[arr > 5] : [6 7 8 9]

boolArr : [False False False False False  True  True  True  True]
arr[boolArr] : [6 7 8 9]

numArr : [5 6 7 8]
arr[numArr] : [6 7 8 9]
